# Generated by Django 4.1.5 on 2023-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coverphoto', models.ImageField(upload_to='movie_covers/')),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('adult', 'Adult'), ('romance', 'Romance'), ('scifi', 'scifi')], default='horror', max_length=10)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('duration', models.TextField(max_length=10)),
                ('link', models.URLField()),
            ],
        ),
    ]
