# Generated by Django 4.1.5 on 2023-02-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coverphoto', models.ImageField(upload_to='serie_covers/')),
                ('genre', models.CharField(choices=[('horror', 'Horror'), ('adult', 'Adult'), ('romance', 'Romance'), ('scifi', 'scifi'), ('animation', 'animation')], default='horror', max_length=10)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('duration', models.TextField(max_length=10)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('horror', 'Horror'), ('adult', 'Adult'), ('romance', 'Romance'), ('scifi', 'scifi'), ('animation', 'animation')], default='horror', max_length=10),
        ),
    ]
