# Generated by Django 4.1.5 on 2023-02-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_serie_alter_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='genre',
            new_name='genres',
        ),
    ]
