# Generated by Django 4.1.5 on 2023-03-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_genre_serie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('horror', 'Horror'), ('adult', 'Adult'), ('romance', 'Romance'), ('scifi', 'scifi'), ('animation', 'animation'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure')], default='horror', max_length=10),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genres',
            field=models.CharField(choices=[('horror', 'Horror'), ('adult', 'Adult'), ('romance', 'Romance'), ('scifi', 'scifi'), ('animation', 'animation'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('documentary', 'Documentary')], default='horror', max_length=20),
        ),
    ]
