# Generated by Django 4.1.5 on 2023-03-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_movie_genre_alter_serie_genres'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='app_movie',
        ),
        migrations.AlterModelTable(
            name='serie',
            table='app_serie',
        ),
    ]
